[package]
name = "EPLMetadataGenerator"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
hex = "0.4.3"
json = "0.12.4"
reqwest = "0.13.1"
roxmltree = "0.21.1"
sha1 = "0.10.6"
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros"] }
